name: curie
description: An open-source app for managing small schools, made with Flutter.
version: 0.2.0-Pre-Alpha

# publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  google_fonts: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

flutter:
  assets:
    - assets/images/
    - assets/database/

  uses-material-design: true
